const supporters = [ // TODO 実際に載せる名前に修正
  "Yukito0597",
  "user_e8a0a92d6ed4",
  "Shogo Onishi",
  "sanchan",
  "masanori noyori",
  "Daimon Tashiro",
  "Yoshiki desu 0807",
  "nozuo",
  "user_e5e50abee374",
  "tomyk2904",
  "xylitol_v",
  "tsugawara",
  "Maya Abe",
  "Takuma Ishibashi",
  "taiyakingu",
  "synrzbhs",
  "ho2k_com",
  "momiagematsuge",
  "doraradora",
  "sou_715",
  "user_1d34cd0d3b64",
  "keimo",
  "spaceshoptokyo",
  "ryuho_drum",
  "osawa_1121",
  "masahiro_ono",
  "yukihikari",
  "gwAa12jpaj",
  "user_df04fcbca344",
  "Fuyo35",
  "kaospacebro2",
  "tokoroten1125",
  "Mizu49",
  "nori_imnnn",
  "Cytl1223",
];

export default supporters;
