const campfireBackers = [
  "のりこ",
  "さんちゃん",
  "教育クリエイター鈴木健太郎",
  "ho2k.com",
  "有吉 志満",
  "塩澤　太基",
  "100 Program",
  "株式会社おおきに　野寄聖統",
  "Mizu49",
  "synrzbhs",
];

const readyforBackers = [
  "Tsubasa Nakamura",
  "森 昭彦",
  "L.K.Mikami",
  "0m1",
  "GemHarada",
  "サリナ",
  "arai",
  "SWFOL1",
  "はまろ",
  "Motty",
  "GoTanda先生",
  "mokochan",
  "こういち",
  "ずし",
  "伊藤 小百合",
  "オオツカクニノリ",
  "t-yashiki",
  "宇宙メルマガTHE VOYAGE編集長",
  "宇宙兄弟担当編集ムネ",
  "lonely2nd",
  "宇宙タレント黒田有彩　-ウーチュー部-",
  "Ruiquita",
  "せいこ",
  "箭内克俊",
  "Jun",
  "Shimokawa",
  "たくや",
  "tsu2020",
  "GoTanda先生",
  "萬徳晃志",
  "TOMOKO",
  "山本将人",
  "福島秀明",
  "鳴瀬 善久",
  "シーゲル　ナガオカ",
  "伊丹 雄太",
  "畠山駿",
  "Naoko Yamazaki",
  "白坂知啓",
  "阿部　智大",
  "宗像靖彦",
  "堀内　涼",
  "小野雅裕",
  "大貫翔太",
  "よへ",
  "Me",
  "TenTem",
  "内山崇",
  "内山崇",
  "りびぃ",
  "田中 克明",
  "yki",
  "しぶちょー",
  "GemHarada",
  "ABLab",
  "とむドラゴン",
  "ho2k.com",
];

const readyforBackersImage = [
  "/images/backers/readyfor/tokyo_gem_science.jpg",
  "/images/backers/readyfor/ivicon_japan.png",
  "/images/backers/readyfor/uchunomise.jpg",
]

export { campfireBackers, readyforBackers, readyforBackersImage };
